Pe ro no/Ass03Solution/eStore/Controllers/LogoutController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace eStore.Controllers
{
    public class LogoutController : Controller
    {
        [Authorize]
        public IActionResult Index()
        {
            HttpContext.SignOutAsync();
            return RedirectToAction("Index", "Login");
        }
    }
}

Pe ro no/Ass03Solution/eStore/Controllers/MemberController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BusinessObject;
using DataAccess.Repository.MemberRepo;
using Microsoft.AspNetCore.Authorization;
using eStore.Models;
using DataAccess.Repository.OrderRepo;
using DataAccess.Repository.OrderDetailRepo;

namespace eStore.Controllers
{
    
    public class MemberController : Controller
    {
        IMemberRepository memberRepository = null;
        public MemberController()
        {
            memberRepository = new MemberRepository();
        }

        [Authorize(Roles = "Admin")]
        // GET: MemberController
        public async Task<IActionResult> Index(string search, int? page)
        {
            if (page == null)
            {
                page = 1;
            }

            IEnumerable<Member> members = memberRepository.GetMembersList().OrderByDescending(mem => mem.Fullname);
            if (!string.IsNullOrEmpty(search))
            {
                members = members.Where(mem => mem.Fullname.ToLower().Contains(search.ToLower()));
                ViewBag.Search = search;
            }

            int pageSize = 10;

            return View(await PaginatedList<Member>.CreateAsync(members.AsQueryable(), page ?? 1, pageSize)) ;
        }

        [Authorize(Roles = "Admin")]
        // GET: MemberController/Details/5
        public ActionResult Details(int? id)
        {
            try
            {
                if (id == null)
                {
                    throw new Exception("Member ID is not found!!!");
                }
                Member member = memberRepository.GetMember(id.Value);
                if (member == null)
                {
                    throw new Exception("Member ID is not found!!!");
                }
                return View(member);
            } catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View();
            }
        }

        [Authorize(Roles = "Admin")]
        // GET: MemberController/Create
        public ActionResult Create()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        // POST: MemberController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Member member, [FromForm] string confirm)
        {
            try
            {
                if (!member.Password.Equals(confirm))
                {
                    throw new Exception("Confirm and Password are not matched!!!");
                }
                if (ModelState.IsValid)
                {
                    memberRepository.AddMember(member);
                }
                Member newMember = memberRepository.GetMember(member.Email);
                TempData["Create"] = "Create Member with the ID <strong>" + newMember.MemberId + "</strong> successfully!!";
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View(member);
            }
        }

        [Authorize(Roles = "Admin")]
        // GET: MemberController/Edit/5
        public ActionResult Edit(int? id)
        {
            try
            {
                if (id == null)
                {
                    throw new Exception("Member ID is not found!!!");
                }
                Member member = memberRepository.GetMember(id.Value);
                if (member == null)
                {
                    throw new Exception("Member ID is not found!!!");
                }
                return View(member);
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View();
            }
        }

        [Authorize(Roles = "Admin")]
        // POST: MemberController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Member member, [FromForm] string confirm)
        {
            try
            {
                if (id != member.MemberId)
                {
                    throw new Exception("Member ID is not matched!! Please try again");
                }
                if (ModelState.IsValid)
                {
                    if (!member.Password.Equals(confirm))
                    {
                        throw new Exception("Confirm and Password are not matched!!!");
                    }
                    memberRepository.UpdateMember(member);
                    TempData["Update"] = "Update Member with the ID <strong>" + id + "</strong> successfully!!";
                }
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View(member);
            }
        }

        [Authorize(Roles = "Admin")]
        // GET: MemberController/Delete/5
        public ActionResult Delete(int? id)
        {
            try
            {
                if (id == null)
                {
                    throw new Exception("Member ID is not found!!!");
                }
                Member member = memberRepository.GetMember(id.Value);
                if (member == null)
                {
                    throw new Exception("Member ID is not found!!!");
                }
                return View(member);
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View();
            }
        }

        [Authorize(Roles = "Admin")]
        // POST: MemberController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            try
            {
                IOrderRepository orderRepository = new OrderRepository();
                IOrderDetailRepository orderDetailRepository = new OrderDetailRepository();

                IEnumerable<Order> orders = orderRepository.GetOrders(id);
                if (orders != null && orders.Any())
                {
                    foreach (var order in orders)
                    {
                        orderDetailRepository.DeleteOrderDetails(order.OrderId);
                    }
                }
                orderRepository.DeleteByMember(id);
                memberRepository.DeleteMember(id);
                TempData["Delete"] = "Delete Member with the ID <strong>" + id + "</strong> successfully!!";
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View();
            }
        }

        [Authorize(Roles = "User")]
        public IActionResult Profile()
        {
            try
            {
                string strMemberId = User.Claims.SingleOrDefault(c => c.Type.Equals("MemberId")).Value;
                Member member = memberRepository.GetMember(int.Parse(strMemberId));
                
                return View(member);
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View();
            }
        }

        [Authorize(Roles = "User")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Profile(Member member, [FromForm] string confirm)
        {
            Request.Headers["Content-Type"] += ";charset=UTF-8";
            Response.Headers["Content-Type"] += ";charset=UTF-8";
            try
            {
                string strMemberId = User.Claims.SingleOrDefault(c => c.Type.Equals("MemberId")).Value;
                int id = int.Parse(strMemberId);

                if (id != member.MemberId)
                {
                    throw new Exception("Member ID is not matched!! Please try again");
                }
                if (ModelState.IsValid)
                {
                    if (!member.Password.Equals(confirm))
                    {
                        throw new Exception("Confirm and Password are not matched!!!");
                    }

                    memberRepository.UpdateMember(member);
                    ViewBag.Success = "Update your Profile successfully!!";
                }
                return View(member);
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View(member);
            }
        }
    }
}

Pe ro no/Ass03Solution/eStore/Controllers/OrderController.cs
using BusinessObject;
using ClosedXML.Excel;
using DataAccess.Repository.OrderDetailRepo;
using DataAccess.Repository.OrderRepo;
using DataAccess.Repository.ProductRepo;
using eStore.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace eStore.Controllers
{
    class OrderExportData
    {
        [Display(Name = "Order ID")]
        public int OrderID { get; set; }

        [Display(Name = "Member Name")]
        public string MemberName { get; set; }

        [Display(Name = "Order Date")]
        public DateTime OrderDate { get; set; }

        [Display(Name = "Order Total")]
        public decimal OrderTotal { get; set; }
    }

    [Authorize]
    public class OrderController : Controller
    {
        private IOrderRepository orderRepository;
        private IOrderDetailRepository orderDetailRepository;

        public OrderController()
        {
            orderRepository = new OrderRepository();
            orderDetailRepository = new OrderDetailRepository();
        }

        
        public async Task<IActionResult> Index(DateTime? start, DateTime? end, int? page)
        {
            try
            {
                ViewBag.Start = (start == null) ? "" : start.Value.Date.ToString("yyyy-MM-dd");
                ViewBag.End = (end == null) ? "" : end.Value.Date.ToString("yyyy-MM-dd");

                if (page == null)
                {
                    page = 1;
                }

                int memberId = int.Parse(User.Claims.First(c => c.Type.Equals("MemberId")).Value);
                IEnumerable<Order> orders = orderRepository.GetOrders(memberId);

                if (start != null && end != null)
                {
                    if (start > end)
                    {
                        DateTime? temp = start;
                        start = end;
                        end = temp;
                    }
                    orders = orderRepository.GetOrders(memberId, start.Value, end.Value);
                }
                else if ((start != null && end == null) || (start == null && end != null))
                {
                    throw new Exception("Please fill both of the Start and End Date inputs to filter or leave them blank!");
                } else if (start == null && end == null)
                {
                    ViewBag.Start = orders.Min(or => or.OrderDate).Date.ToString("yyyy-MM-dd");
                    ViewBag.End = orders.Max(or => or.OrderDate).Date.ToString("yyyy-MM-dd");
                }

                List<OrderExportData> orderExport = new List<OrderExportData>();
                
                foreach (var order in orders)
                {
                    decimal total = orderDetailRepository.GetOrderTotal(order.OrderId);
                    ViewData[order.OrderId.ToString()] = Math.Round(total, 2);
                    orderExport.Add(new OrderExportData
                    {
                        OrderID = order.OrderId,
                        MemberName = order.Member.Fullname,
                        OrderDate = order.OrderDate,
                        OrderTotal = total
                    });
                }
                HttpContext.Session.SetComplexData("OrderData", orderExport);
                int pageSize = 10;

                return View(await PaginatedList<Order>.CreateAsync(orders.AsQueryable(), page ?? 1, pageSize));
            } catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View();
            }
        }

        public ActionResult Details(int? id)
        {
            try
            {
                if (id == null)
                {
                    throw new Exception("Order ID is not found!!!");
                }
                Order order = orderRepository.GetOrder(id.Value);
                
                if (order == null)
                {
                    throw new Exception("Product ID is not found!!!");
                }
                order.OrderDetails = orderDetailRepository.GetOrderDetails(order.OrderId).ToList();
                decimal orderTotal = orderDetailRepository.GetOrderTotal(order.OrderId);
                ViewBag.OrderTotal = orderTotal;
                return View(order);
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View();
            }
        }

        public IActionResult Delete(int? id)
        {
            try
            {
                if (id == null)
                {
                    throw new Exception("Order ID is not existed!!");
                }
                Order order = orderRepository.GetOrder(id.Value);
                if (order == null)
                {
                    throw new Exception("Order ID is not existed!!");
                }
                order.OrderDetails = orderDetailRepository.GetOrderDetails(order.OrderId).ToList();
                decimal orderTotal = orderDetailRepository.GetOrderTotal(order.OrderId);
                ViewBag.OrderTotal = orderTotal;
                return View(order);
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            try
            {
                Order order = orderRepository.GetOrder(id);
                if (order == null)
                {
                    throw new Exception("Order ID is not existed!!");
                }
                orderDetailRepository.DeleteOrderDetails(id);
                orderRepository.DeleteOrder(id);
                TempData["Delete"] = "Delete Order with the ID <strong>" + id + "</strong> successfully!!";
                return RedirectToAction(nameof(Index));
            } catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View();
            }
        }
    }
}

Pe ro no/Ass03Solution/eStore/Views/Shared/Alert.cshtml
@{
    var role = ViewData["role"];
    var message = ViewData["message"];
    string roleClass = string.Empty;

    <div class="alert alert-@role" role="alert">
        @Html.Raw(message.ToString())

        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}

Pe ro no/Ass03Solution/eStore/Views/Shared/_Layout.cshtml
@using System.Security.Claims
 
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - eStore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar fixed-top navbar-expand-lg navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">eStore</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.Identity.IsAuthenticated)
                        {
                            @if (User.Claims.FirstOrDefault(c => c.Type.Equals(ClaimTypes.Name)).Value.Equals("Admin"))
                            { // Admin
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Member" asp-action="Index">Member Management</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Product" asp-action="Index">Product Management</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Order" asp-action="Index">Order Management</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Logout" asp-action="Index">Log Out</a>
                                </li>
                            }
                            else
                            { // User
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Product" asp-action="Index">Shopping</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Cart" asp-action="Index">View Cart</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Order" asp-action="Index">My Orders</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Member" asp-action="Profile">Your Profile</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Logout" asp-action="Index">Log Out</a>
                                </li>
                            }
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - eStore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>